### ISSUE TITLE
TensorRT example - archive?

### ISSUE THREAD

**Issue by FabiEder** [NVIDIA/gpu-rest-engine#12]
Hey,

I would like to run the tensorRT example, everything looks fine but I don´t know where to get the archive? The Dockerfile states the following:

```
# Require the TensorRT archive to be present in the build context.
ADD TensorRT-2.1.0.x86_64.cuda-8.0.tar.bz2 /opt/
```

On the TensorRT page I can only download a .deb file. I am also attending the early access program for TensorRT 2, and the current version is 2.0.2-1, so it´s officially not even at 2.1 yet..

Help would be much appreciated!

**Comment by cgottbrath-nvidia** [comment]
It will be available publicly very soon (we have one blocker bug we are tying down). 

-Chris

**Comment by drewfarris** [comment]
@FabiEder take a look at #14 - this employs TensorRT 2.1.2 that was announced 6/27

**Comment by nicolasmetallo** [comment]
If you download what @drewfarris mentioned and change the path, it works! 

My problem is when I want to use a custom model (sometimes trained with DIGITS) and it keeps giving me this error. Is there a workaround?

Thanks!!

`2017/07/05 20:11:53 Initializing TensorRT classifiers
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fb7f2c85152]`
