### ISSUE TITLE
Will GRE or tensorRT support caffe2?

### ISSUE THREAD

**Issue by OdinLin** [NVIDIA/gpu-rest-engine#13]
GRE  currently is supporting Caffe, It would be great if support caffe2 framework, any plan?

**Comment by flx42** [comment]
@cgottbrath-nvidia can you answer this question?

**Comment by cgottbrath-nvidia** [comment]
For GRE .. no plans. But it is open source. I would love to see someone adapt it for C2. TensorRT can be used with C2 today using the C++ graph definition API. We are working on an export path for C2 models into TensorRT, so watch for updates in that area.

**Comment by flx42** [comment]
Thanks @cgottbrath-nvidia!
