### ISSUE TITLE
GRE Outputs wrong labels

### ISSUE THREAD

**Issue by wellarno** [NVIDIA/gpu-rest-engine#21]
Hello, I made my own DIGITS Model with GoogLeNet and implemented it in GRE, adding the files to Docker and changing the Dockerfile.caffe_server so that it should use my Model-files.

After sending one image to GRE via CURL, it outputs always the same label as the highest-confidence-one, exactly that label that has the first position in the "labels.txt". The following confidences are more or less random labels.

I already changed the labels.txt to verify this and GRE told me the new "first" label for the exact same image with the exact same percentage.

Anyone encountered a similar problem and maybe got a solution for this?

The same images were identified correctly on DIGITS itself.

Thanks in advance!

**Comment by flx42** [comment]
The image pre-processing steps might be different than DIGITS. GRE is not very generic on this side.
Does GoogleNet have multiple output layers also?

**Comment by wellarno** [comment]
Well it's output is made by one Pooling-Layer followed by one FC-Layer and a Softmax-activation with the Softmax distributing the output in the end.

I could try my model with AlexNet if GRE fits AlexNet better.

**Comment by flx42** [comment]
This code is provided as a demo to help people get started, it was not designed to be a general solution.

Sorry for the very long delay in answering.
