### ISSUE TITLE
How to access specific jobID of digits models through the GPU-rest-engine

### ISSUE THREAD

**Issue by rperdon** [NVIDIA/gpu-rest-engine#22]
I have some models trained in Digits which I would like to access using the GPU-rest-engine. I can access them via curl commands of the built Digits REST API, but find it lacking in performance. A nvidia support contact showed me the GRE and I am interested in utilizing this for my model deployments.

**Comment by flx42** [comment]
There is a way to export models from the DIGITS UI. There is probably a underlying REST API call that you can use to do that programmatically. You should ask the DIGITS team if you have issues with that.
