### ISSUE TITLE
Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by rperdon** [NVIDIA/gpu-rest-engine#23]
Installed CUDA 9.0 package and driver. Installed cudnn 7.0. 

Checked install, of libcudnn, seems ok. LD_LIBRARY_PATH is set correctly I think and files seems to be ok spot.
root@Hackathon:/home/cpcmecadmin/caffe/build# check libcudnn 
	libcudnn.so.7 -> libcudnn.so.7.0.5
	libcudnn.so.7 -> libcudnn.so.7.0.5
	libcudnn.so.5 -> libcudnn.so.5.1.10
libcudnn is installed

When trying to run docker run --runtime=nvidia --name=server --net=host --rm inference_server I get the above error. Any thoughts?

**Comment by flx42** [comment]
Oh, I messed up the Dockerfile I think, will fix.

**Comment by flx42** [comment]
Fixed. Please test @rperdon
