### ISSUE TITLE
Regarding instructions of loading in a Digits model into GRE

### ISSUE THREAD

**Issue by rperdon** [NVIDIA/gpu-rest-engine#24]
https://github.com/NVIDIA/gpu-rest-engine/issues/4

I was looking at this instruction and tried following the links to modification of the deploy file and found error 404 on those links. Can you provide the modifications necessary to the prototxt files that are necessary for GRE to utilize an exported Digits model?

**Comment by flx42** [comment]
Look at those lines:
https://github.com/NVIDIA/gpu-rest-engine/blob/722f3597f8a47881c2d7bd9fe7fecd86f2fba0a6/Dockerfile.caffe_server#L96-L103

**Comment by rperdon** [comment]
Is there a way to load more than one model into the GRE?

**Comment by flx42** [comment]
It will require modifying the golang code, but it's totally possible. Adding new endpoints handlers is quite easy in go.

Another option is to run N different containers (one for each model) listening on different ports (e.g. 8000, 8001, 8002...). Then you put an nginx reverse-proxy on top that dispatches to the right server based on the URI, you have examples on the CLI:
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass

**Comment by rperdon** [comment]
Would I be modifying the main.go file in the gpu-rest-engine/caffe folder?
