### ISSUE TITLE
GRE and windows support

### ISSUE THREAD

**Issue by rperdon** [NVIDIA/gpu-rest-engine#29]
I'm working on doing a demo of our carving tool, GRE and model support. My normal setup would be to have a vm for linux with the model serve answering the carving tool (windows app). I wonder if there would be a way to get it running with windows docker. 

So far I'm stuck with the problem of the nvidia-container-runtime bug where it indicates unknown runtime specified nvidia. On the linux side, we added a line to the daemon.json pointing to the nvidia-container-runtime, but I don't think such a container exists on the windows side. It would save a linux install and simplify the deployment of our carving/classification tool if I can have an all windows install.

**Comment by flx42** [comment]
Maybe with an Hyper-V VM with DDA (direct-device assignment), you would be running Linux containers on Windows. But I have no experience with this and I'm not even sure that's possible (and it requires Windows Server).
On Windows, you would have to get bare metal.

**Comment by rperdon** [comment]
We have windows 2016 licenses (not sure if my surface book 2 will work well with it) I'd be willing to be a guinea pig to develop this.

**Comment by flx42** [comment]
You can look at the many existing issues on the nvidia-docker repository:
https://github.com/NVIDIA/nvidia-docker/issues/429
https://github.com/NVIDIA/nvidia-docker/issues/197

I gave you everything I know so far ;)
You will have to look at the [DDA documentation](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/deploying-graphics-devices-using-dda) and assign the discrete GPU to the Hyper-V Linux VM.
