### ISSUE TITLE
Error on trying to add TensorRT in compilation

### ISSUE THREAD

**Issue by brandonjabr** [NVIDIA/gpu-rest-engine#31]
Running either of the first two commands in the instructions via docker on Ubuntu 16.04 gives me the following error:

Step 10/18 : ADD TensorRT-2.1.2.x86_64.cuda-8.0-16-04.tar.bz2 /opt/
ADD failed: stat /var/lib/docker/tmp/docker-builder161170432/TensorRT-2.1.2.x86_64.cuda-8.0-16-04.tar.bz2: no such file or directory

Any idea what the issue is? Thanks in advance.

**Comment by flx42** [comment]
TensorRT needs to be downloaded separately. But you would need to change this line anyway since a new version has been released since.
