### ISSUE TITLE
an error of  trt.utils.uff_to_trt_engine()

### ISSUE THREAD

**Issue by fujingling** [NVIDIA/gpu-rest-engine#33]
I got a error when I transfer a tensorflow model to TensorRT, The flowing is my error info:

Traceback (most recent call last):
  File "pnet_to_rt.py", line 116, in <module>
    main()
  File "pnet_to_rt.py", line 102, in main
    engine = trt.utils.uff_to_trt_engine(G_LOGGER, uff_model,parser,MAX_BATCHSIZE,MAX_WORKSPACE)
  File "/export/home/aiusr/fujingling/env/img/lib/python2.7/site-packages/tensorrt/utils/_utils.py", line 175, in uff_to_trt_engine
    if datatype == infer.DataType.HALF and not builder.platform_has_fast_fp16():
TypeError: Not a tuple or list

The Flowing is my register_input,my Tensorflow model has 3 Placeholder,so I have to set 3 register_input.
parser.register_input("input_image", (3, 196, 240), 0)
parser.register_input("image_width", (1), 1) 
parser.register_input("image_height", (1),2)

who knows how can I solve this problem?

**Comment by flx42** [comment]
Sorry, you would have to ask the TensorRT developers. Try the NVIDIA devtalk forum.
https://devtalk.nvidia.com/
