### ISSUE TITLE
TensorRT server issue

### ISSUE THREAD

**Issue by rperdon** [NVIDIA/gpu-rest-engine#36]
Step 10/18 : ADD TensorRT-2.1.2.x86_64.cuda-8.0-16-04.tar.bz2 /opt/
ADD failed: stat /var/lib/docker/tmp/docker-builder687990407/TensorRT-2.1.2.x86_64.cuda-8.0-16-04.tar.bz2: no such file or directory

Tried a clean download on two different servers, unable to get past this step. suspect TensorRT 2.1.2 not available for download now.

**Comment by ryanolson** [comment]
https://github.com/NVIDIA/gpu-rest-engine/blob/master/Dockerfile.tensorrt_server#L45

It's expected you put the tarball in the build path.

**Comment by rperdon** [comment]
Downloaded and added to build path. Thx.
