### ISSUE TITLE
Using DIGITS trained network in rest engine

### ISSUE THREAD

**Issue by emerysilb** [NVIDIA/gpu-rest-engine#4]
Hello, I am trying to use a DIGITS trained network in this gpu-rest-engine and I am having some issues setting up the docker container with the pre-trained network. What is the best way for importing the pre-trained network into the rest engine for processing? 

Thank you!

**Comment by flx42** [comment]
Hello,

First, remove the bundled caffenet model, you won't need it. Remove [these lines](https://github.com/NVIDIA/gpu-rest-engine/blob/master/Dockerfile.inference_server#L55-L57)

And then, you should use a [Docker volume](https://docs.docker.com/engine/tutorials/dockervolumes/) to expose the trained model inside the container.
For instance:
```
-v /home/felix/models:/models
```
Finally, modify the paths used at the [end of the Dockerfile](https://github.com/NVIDIA/gpu-rest-engine/blob/master/Dockerfile.inference_server#L74-L78) to point to the model you want to use, for instance: 
```
/models/mydigitsmodel/deploy.prototxt
```

**Comment by emerysilb** [comment]
Thank you so much! This program is awesome!!!
