### ISSUE TITLE
requisitions

### ISSUE THREAD

**Issue by jadsongmatos** [NVIDIA/gpu-rest-engine#42]
Is it possible to use GPU to speed up requests? Would there be any simpler demonstration like just hello world?

**Comment by flx42** [comment]
Sorry, I don't understand your question.

> Is it possible to use GPU to speed up requests?

Which part of the request do you want to speed up?

**Comment by jadsongmatos** [comment]
all parts, from routes to assembly of responses

**Comment by flx42** [comment]
Ok, I'm not sure there is any example of this to be honest.

You should ask your question (and provide more details) here: https://github.com/NVIDIA/triton-inference-server
(if it relates to deep learning at all)

**Comment by flx42** [comment]
The name of this repository might be a bit misleading by the way; this is still doing the HTTP processing on the CPU side; but offloading the deep learning inference to the GPU.

**Comment by jadsongmatos** [comment]
So I was wrong about the purpose of the project, I thought GPU REST was about speeding HTTP requests.
Can I seriously speed up HTTP responses using GPU? If yes, there is a project about it.

**Comment by flx42** [comment]
>  Can I seriously speed up HTTP responses using GPU? If yes, there is a project about it.

Not that I know of. But if you're interested in network processing offload with GPUs, there is the NVIDIA Aerial product for **5G packets**:
https://developer.nvidia.com/aerial-sdk
